---

name: Packaging

on:
  workflow_call:

defaults:
  run:
    shell: sh -ex {0}

env:
  # TODO: stonking current untested: https://warthogs.atlassian.net/browse/UPRO-1274
  DEVELOPMENT_RELEASE: 'stonking'

jobs:
  build:
    name: Build (${{ matrix.release }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # TODO test on stonking: https://warthogs.atlassian.net/browse/UPRO-1274
        release: ['bionic', 'focal', 'jammy', 'noble', 'resolute']
    steps:
      - name: Prepare build tools
        env:
          DEBFULLNAME: GitHub CI Auto Builder
          DEBEMAIL: nobody@nowhere.invalid
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy install --no-install-recommends sbuild schroot ubuntu-dev-tools debootstrap git-buildpackage
          sudo sbuild-adduser $USER
          cp /usr/share/doc/sbuild/examples/example.sbuildrc /home/$USER/.sbuildrc
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Build package
        env:
          DEBFULLNAME: GitHub CI Auto Builder
          DEBEMAIL: nobody@nowhere.invalid
        run: |
          gbp dch --ignore-branch --snapshot --distribution=${{ matrix.release }}
          dch --local=~${{ matrix.release }} ""
          if [ "${{ matrix.release }}" = "${{ env.DEVELOPMENT_RELEASE }}" ]; then
            SKIP_PROPOSED=""
          else
            SKIP_PROPOSED="--skip-proposed"
          fi
          sg sbuild -c "mk-sbuild $SKIP_PROPOSED ${{ matrix.release }}"
          sg sbuild -c "sbuild --dist='${{ matrix.release }}' --resolve-alternatives --no-clean-source --nolog --verbose --no-run-lintian --build-dir='${{ runner.temp }}'"
          mv ../*.deb '${{ runner.temp }}'  # Workaround for Debbug: #990734, drop in Jammy
      - name: Archive debs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'ci-debs-${{ matrix.release }}'
          path: '${{ runner.temp }}/*.deb'
          retention-days: 3
