---

name: Unit Tests

on:
  workflow_call:

defaults:
  run:
    shell: sh -ex {0}

jobs:
  unit-tests:
    name: tox -e test
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy install tox libapt-pkg-dev
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Unit
        run: tox -e test
